language: python
python:
  - "3.6"
install: "pip install -r requirements/testing.txt"
before_script:
  - python manage.py migrate
script:
  - flake8
  - coverage run manage.py test --settings=config.settings.production
after_success:
  - coveralls
