# Generated by Django 2.0.3 on 2018-04-07 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'description',
                    models.TextField(blank=True, null=True),
                ),
                (
                    'logo',
                    models.ImageField(blank=True, null=True, upload_to=''),
                ),
                (
                    'name',
                    models.CharField(max_length=255),
                ),
                (
                    'slug',
                    models.SlugField(max_length=255),
                ),
                (
                    'website',
                    models.URLField(blank=True, null=True),
                ),
                (
                    'creation_timestamp',
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    'update_timestamp',
                    models.DateTimeField(auto_now=True),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='companies_that_i_own',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['owner'], name='companies_c_owner_i_f8927e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('owner', 'slug')},
        ),
    ]
