import os

from .base import *  # noqa: F401,F403


CSRF_COOKIE_SECURE = True
DEBUG = False
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_SECONDS = 3600
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
X_FRAME_OPTIONS = 'DENY'

ALLOWED_HOSTS = os.environ['ALLOWED_HOSTS'].split(' ')
SECRET_KEY = os.environ['SECRET_KEY']
